config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'is already in the list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_new.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "slect2" } } %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
      </div>
      <div class="modal-footer">
          <%= f.submit "Add movie", class: "btn btn-flat" %>
        <% end %>
        <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3>Add a movie to your <%= @list.name %> list</h3>
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.association :movie, prompt: "Select a movie" %>
            <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
            <%= f.submit class: 'btn btn-primary' %>
          <% end %>

        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Insert a name' %>
          <%= f.input :description, placeholder: 'Insert a description' %>
          <%= f.input :photo, as: :file %>
          <div class="d-flex">
          <%= f.submit class: 'm-3 btn btn-primary' %>
        <% end %>
        <%= link_to "Back to lists", lists_path, class: "m-3 btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<h1>Edit List!</h1>

<%= render "form", restaurant: @restaurant %>

app/views/lists/index.html.erb
<div class="home-appear">

  <div class="title-img ">
    <%= image_tag "title.png", class: 'rounded mx-auto d-block', :alt => "rss feed" %>
  </div>

  <div class="show-cards">
    <div class="cards">
      <% @lists.each do |list| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(
          <%if list.photo.attached? %>
            <%= cl_image_path(list.photo.key) %>
          <% else  %>
              <%= asset_path 'moviebg.jpg' %>
          <% end %>);">
          <%= link_to list.name, list_path(list) %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to "New List", new_list_path, class: "m-2 btn btn-primary" %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Insert a name' %>
          <%= f.input :description, placeholder: 'Insert a description' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
        <%= link_to "Back to lists", lists_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(
  <%if @list.photo.attached? %>
   <%= cl_image_path(@list.photo.key) %>
  <% else  %>
  <%= asset_path 'moviebg.jpg' %>
<% end %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
    <p><%= @list.description %></p>
    <p class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></p>
  </div>
</div>

<div class="container py-5">

  <div class="card-grid">
    <% @list.bookmarks.each do |bookmark| %>

      <div class="card-trip">
        <%=image_tag bookmark.movie.poster_url %>
        <div class="card-trip-infos">
          <div>
            <h2><%= bookmark.movie.title %></h2>
            <p><%= bookmark.comment %> </p>
            <p><%= "Rating: #{bookmark.movie.rating}" %> </p>
            <%= link_to "", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "fa-solid fa-trash" %>
          </div>
        </div>
      </div>

      <li class='list-group-item'> <%=  %>

      <% end %>
    </div>

    <%= link_to "Back to list", lists_path, class: "btn btn-primary" %>

    <%= link_to "delete this list", list_path(@list), class: "btn btn-primary", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    <%# add a movie %>

    <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary"%>
    <%= link_to "Edit List", edit_list_path(@list), class: "btn btn-primary"%>

  </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Welcome to your favorite <i class="fa-solid fa-film"></i> watch list!
  </div>
</div>